#!/bin/bash

# Auto-Build Environment Setup
# Spec: 010 - Amélioration de la Page 404
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: 010 - Page 404 Improvement"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Navigate to project root
PROJECT_ROOT="/Applications/Sites/Moderna_twig/thelia"
TEMPLATE_ROOT="$PROJECT_ROOT/templates/frontOffice/moderna"

echo -e "${BLUE}Project Root:${NC} $PROJECT_ROOT"
echo -e "${BLUE}Template Root:${NC} $TEMPLATE_ROOT"
echo ""

# ============================================
# STEP 1: CHECK DDEV STATUS
# ============================================
echo -e "${YELLOW}Step 1: Checking DDEV status...${NC}"

cd "$PROJECT_ROOT"

if ddev describe > /dev/null 2>&1; then
    echo -e "${GREEN}✓ DDEV is running${NC}"
else
    echo -e "${YELLOW}Starting DDEV...${NC}"
    ddev start
    echo -e "${GREEN}✓ DDEV started${NC}"
fi

# ============================================
# STEP 2: CLEAR CACHE
# ============================================
echo ""
echo -e "${YELLOW}Step 2: Clearing Thelia cache...${NC}"

ddev exec rm -rf var/cache/*
echo -e "${GREEN}✓ Cache cleared${NC}"

# ============================================
# STEP 3: BUILD TEMPLATE ASSETS (if needed)
# ============================================
echo ""
echo -e "${YELLOW}Step 3: Checking template assets...${NC}"

if [ -d "$TEMPLATE_ROOT/node_modules" ]; then
    echo -e "${GREEN}✓ Node modules already installed${NC}"
else
    echo -e "${YELLOW}Installing npm dependencies...${NC}"
    ddev exec bash -c "cd templates/frontOffice/moderna && npm install"
    echo -e "${GREEN}✓ Dependencies installed${NC}"
fi

# Build assets
echo -e "${YELLOW}Building template assets...${NC}"
ddev exec bash -c "cd templates/frontOffice/moderna && npm run build"
echo -e "${GREEN}✓ Assets built${NC}"

# ============================================
# STEP 4: VERIFY TRANSLATION FILES
# ============================================
echo ""
echo -e "${YELLOW}Step 4: Verifying translation files...${NC}"

TRANSLATIONS_DIR="$TEMPLATE_ROOT/translations"
TRANSLATION_FILES=("messages.fr_FR.yaml" "messages.en_US.yaml" "messages.es_ES.yaml" "messages.it_IT.yaml")

for file in "${TRANSLATION_FILES[@]}"; do
    if [ -f "$TRANSLATIONS_DIR/$file" ]; then
        echo -e "${GREEN}✓ $file exists${NC}"
    else
        echo -e "${RED}✗ $file missing${NC}"
    fi
done

# ============================================
# STEP 5: VERIFY 404 PAGE
# ============================================
echo ""
echo -e "${YELLOW}Step 5: Verifying 404 template...${NC}"

if [ -f "$TEMPLATE_ROOT/404.html.twig" ]; then
    LINES=$(wc -l < "$TEMPLATE_ROOT/404.html.twig" | tr -d ' ')
    echo -e "${GREEN}✓ 404.html.twig exists ($LINES lines)${NC}"
else
    echo -e "${RED}✗ 404.html.twig missing${NC}"
fi

# ============================================
# SUMMARY
# ============================================
echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Site URLs:"
echo "  Main Site: https://thelia3-moderna.ddev.site"
echo "  404 Page:  https://thelia3-moderna.ddev.site/test-404-page"
echo ""
echo "Files to modify:"
echo "  - $TEMPLATE_ROOT/404.html.twig"
echo "  - $TEMPLATE_ROOT/translations/messages.fr_FR.yaml"
echo "  - $TEMPLATE_ROOT/translations/messages.en_US.yaml"
echo "  - $TEMPLATE_ROOT/translations/messages.es_ES.yaml"
echo "  - $TEMPLATE_ROOT/translations/messages.it_IT.yaml"
echo ""
echo "After making changes, clear cache with:"
echo "  ddev exec rm -rf var/cache/*"
echo ""
