#!/bin/bash

# Auto-Build Environment Setup for WishlistModerna Module
# Generated by Planner Agent
# Spec: 013-nous-devons-cr-er-un-module-pour-la-fonctionnalit-

set -e

echo "========================================"
echo "WishlistModerna Module Development Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# CHECK DDEV STATUS
# ============================================

echo ""
echo "Checking DDEV status..."

if ! command -v ddev &> /dev/null; then
    echo -e "${RED}DDEV is not installed. Please install DDEV first.${NC}"
    exit 1
fi

cd /Applications/Sites/Moderna_twig/thelia

# Check if DDEV is running
if ! ddev describe > /dev/null 2>&1; then
    echo "Starting DDEV..."
    ddev start
else
    echo -e "${GREEN}DDEV is already running${NC}"
fi

# ============================================
# VERIFY DATABASE CONNECTION
# ============================================

echo ""
echo "Verifying database connection..."

if ddev mysql -e "SELECT 1" > /dev/null 2>&1; then
    echo -e "${GREEN}Database connection OK${NC}"
else
    echo -e "${RED}Database connection failed${NC}"
    exit 1
fi

# ============================================
# CHECK EXISTING WISHLIST TABLE
# ============================================

echo ""
echo "Checking for existing customer_wishlist table..."

if ddev mysql -e "DESCRIBE customer_wishlist" > /dev/null 2>&1; then
    echo -e "${GREEN}customer_wishlist table exists${NC}"
    echo "Existing data will be preserved during module activation."
else
    echo -e "${YELLOW}customer_wishlist table does not exist yet${NC}"
    echo "It will be created when WishlistModerna module is activated."
fi

# ============================================
# CHECK REFERENCE MODULE
# ============================================

echo ""
echo "Checking RecentlyViewedModerna reference module..."

if [ -d "local/modules/RecentlyViewedModerna" ]; then
    echo -e "${GREEN}RecentlyViewedModerna module found at local/modules/${NC}"
    echo "This module will be used as a reference pattern."
else
    echo -e "${YELLOW}RecentlyViewedModerna not found in local/modules/${NC}"
    if [ -d "vendor/thelia/modules/RecentlyViewedModerna" ]; then
        echo -e "${GREEN}Found in vendor/thelia/modules/${NC}"
    else
        echo -e "${RED}RecentlyViewedModerna not found - patterns may not be available${NC}"
    fi
fi

# ============================================
# CLEAR CACHE
# ============================================

echo ""
echo "Clearing Thelia cache..."
ddev exec rm -rf var/cache/*
echo -e "${GREEN}Cache cleared${NC}"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project URL: https://thelia3-moderna.ddev.site"
echo ""
echo "Key Directories:"
echo "  Module target:    local/modules/WishlistModerna/"
echo "  Pattern source:   local/modules/RecentlyViewedModerna/"
echo "  Source controller: templates/frontOffice/moderna/src/Api/WishlistController.php"
echo ""
echo "Useful Commands:"
echo "  ddev exec php Thelia module:refresh       # Refresh module list"
echo "  ddev exec php Thelia module:activate WishlistModerna    # Activate module"
echo "  ddev exec rm -rf var/cache/*              # Clear cache"
echo "  ddev mysql                                # Access MySQL CLI"
echo ""
echo "API Endpoints (after module activation):"
echo "  POST /api/wishlist/sync   - Sync local wishlist with server"
echo "  POST /api/wishlist/add    - Add product to wishlist"
echo "  POST /api/wishlist/remove - Remove product from wishlist"
echo "  POST /api/wishlist/clear  - Clear all wishlist items"
echo ""
