#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 011 - Favorites Page Enhancement

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: 011 - Amélioration de la Page Favoris"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check if DDEV is available
if ! command -v ddev &> /dev/null; then
    echo -e "${RED}Error: DDEV is not installed or not in PATH${NC}"
    exit 1
fi

# ============================================
# START DDEV SERVICES
# ============================================

echo ""
echo "Starting DDEV..."
ddev start

# Check if DDEV started successfully
if [ $? -ne 0 ]; then
    echo -e "${RED}Failed to start DDEV${NC}"
    exit 1
fi
echo -e "${GREEN}DDEV started successfully${NC}"

# ============================================
# BUILD ASSETS
# ============================================

echo ""
echo "Building frontend assets..."
ddev exec bash -c "cd templates/frontOffice/moderna && npm install"
ddev exec bash -c "cd templates/frontOffice/moderna && npm run build"

if [ $? -ne 0 ]; then
    echo -e "${RED}Failed to build assets${NC}"
    exit 1
fi
echo -e "${GREEN}Assets built successfully${NC}"

# ============================================
# CLEAR CACHE
# ============================================

echo ""
echo "Clearing Thelia cache..."
ddev exec rm -rf var/cache/*
echo -e "${GREEN}Cache cleared${NC}"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Thelia Frontend: https://thelia3-moderna.ddev.site"
echo "  Wishlist Page:   https://thelia3-moderna.ddev.site/?view=wishlist"
echo ""
echo "Files to modify:"
echo "  - wishlist.html.twig"
echo "  - components/Product/RecentlyViewed.html.twig"
echo ""
echo "After making changes:"
echo "  1. Rebuild assets: ddev exec bash -c \"cd templates/frontOffice/moderna && npm run build\""
echo "  2. Clear cache:    ddev exec rm -rf var/cache/*"
echo ""
